### ISSUE TITLE
Ma ktoś pomysł na tłumaczeni?

### ISSUE THREAD

**Issue by Borgsc2** [Kiwiutek/Oxygen-Not-Included-Spolszczenie#14]
Mały edit:
Ma ktoś myśl jak przetłumaczyć tekst: "Get your colony all pumped up!" (rejon linii 1619) mam wrażenie że odnosi się do koloni Duplikantów, natomiast co jest problemem znajduje się w klasie tekstów przypisanych do Pompy Gazowej. Dodatkowo dobranie kontekstu tłumaczenia komplikuje to, że na tą chwile nie zauważyłem miejsca, w którym tekst ten by się pojawiał w grze. 
Pominę już w miarę dosłowne tłumaczenie "Weź swoją kolonię i ją przepompuj" ;)

Mam jeszcze jedno pytanie. Ile z tłumaczących osób po za mną posiada jeszcze grę aby weryfikować jak wygląda tłumaczenie.
Niestety ale niektóre teksty po przetłumaczeniu na polski nie mieszczą się w miejscu do tego przeznaczonym :) i będzie trzeba znaleźć na to rozwiązanie albo na zasadzie tłumaczeń alternatywnych lub skróceniu tłumaczenia.

Dodałem w roboczej wersji tłumaczenia jeszcze jedno info w grze o Lokalizacji językowej co pokazuje jeden ze zrzutów ekranu.
![20170312142609_1](https://cloud.githubusercontent.com/assets/5678100/23832190/4a7d3a56-0730-11e7-9ea2-33d302da10db.jpg)
![20170312142644_1](https://cloud.githubusercontent.com/assets/5678100/23832193/4fb26960-0730-11e7-8831-277fc6c2081d.jpg)

**Comment by Stashkin** [comment]
Zgniatarka magazynowa? No proszę Was... ;) MAGAZYN.

Mam zbyt mało czasu, by testować PL w grze, ale na pewno do zmiany jest ta cała informacja o polskiej lokalizacji. Bo po prostu źle brzmi po polsku, jest sporo błędów. Może dziś uda mi się zaproponować poprawkę.

Font może jeszcze ulec zmianie, więc nie ma co robić ciśnienia na zbyt długie nazwy, JEDNAK warto je skracać jak się tylko da w miarę możliwości.

"Get your colony all pumped up!" to skomplikowany zwrot. Zostawiłbym na koniec, albo jak komuś coś do głowy wpadnie. Pewnie trzeba będzie wymyślić coś w całości po polsku, np. "Zbuduj tętniącą tlenem kolonię!".

Dodam jeszcze, że partycypujący w lokalizacji powinni być wymieniani alfabetycznie. Taka dobra praktyka ;)

**Comment by Borgsc2** [comment]
Z tym magazynem to wiem spoko :), rzuciło mi się tylko jako pierwsze do pokazania że tam gdzie się da musimy już teraz wyłapywać takie anomalie Zgniatarka Magazynowa nie została jeszcze zmieniona, bo pracując na pliku jeszcze do tego nie dotarłem, a zabierając się za edycję zapominam, biorąc też pod uwagę, że korzystam z Notepad+ do edycji, też nie chcę skakać z jednego końca pliku na drugi :). Co to tego zwrotu cóż problem w tym, że na ta chwilę wydaje się jeszcze nie być nigdzie wykorzystywany, a jeśli nie wiemy gdzie on będzie to też jestem zdania aby go zostawić bo później może się okazać, że jak już to miejsce się ujawni  nie będzie miał on tam żadnego sensu. 

Tekst o pracach nad lokalizacja jest oczywiście przykładem więc każda zmiana jak najbardziej pożądana. Co do kolejności nie przykładałem do tego uwagi po prostu w ziołem w kolejności jakiej pojawiamy się na github.

**Comment by Borgsc2** [comment]
Co do tych zbyt długich tekstów, może spróbować jakoś zadać pytanie deweloperom, tylko musiał by to zrobić osoba, która dobrze ogarnia angielski :). Po za tym takie pytanie zwróciło by ich uwagę już teraz, że taki problem się pojawia.

**Comment by Kiwiutek** [comment]
Na razie nic nie skracajmy. Trzeba zaczekać jaka czcionka będzie ostatecznie, bo już raz zmienili.
