### ISSUE TITLE
WAŻNE! Podział obowiązków

### ISSUE THREAD

**Issue by Stashkin** [Kiwiutek/Oxygen-Not-Included-Spolszczenie#21]
Główny plik strings.po został podzielony na części po 1000 linijek. Dajcie znać w komentarzach, kto za które linijki chce się zabrać. Taki podział pozwoli na uniknięcie problemów z tłumaczeniami naraz wielu osób ;)

0 - 1k = @MrSidoruk
1k - 2k = @MrSidoruk 
2k - 3k = @MrSidoruk 
3k - 4k = @MrSidoruk 
4k - 5k = @Borgsc2 
5k - 6k = 
6k - 7k = 
7k - 8k = @Viking-90 
8k - 9k = @Viking-90 
9k - 10k = @Viking-90 
10k - 11k = @Stashkin
11k - 12k = @Stashkin
12k - 13k = @Stashkin
13k - 14k = @Stashkin
14k - 15k = @Stashkin
15k - 16253 =

**Comment by MrSidoruk** [comment]
To ja się zajmę od 0 do 4k.

**Comment by Borgsc2** [comment]
usiądę nad liniami 4 do 7k

**Comment by Borgsc2** [comment]
Małe pytanie. 
Pytanie związane jest z kwestią poruszoną przez Staszka na ostatnim filmiku ONI. Mówiłeś tam, że liczysz na pomoc osób z zaawansowaną znajomością angielskiego. Nie będę oszukiwał, że ja głównie posługuje się translatorem i na bazie tego co mi proponuje szukam odpowiedniego znaczenia, na bazie swojego doświadczenia, jak i tego w jakim sensie został tekst użyty w grze. Teksty z którymi mam problem zostawiam. To wszystko po to aby nie zostawić kwiatków typu "Zgniatarka Magazynowa" co już samo w sobie brzmi głupio.
Dlatego głównie pytanie do Ciebie Staszku. Czy chcesz abym dalej pomagał w tłumaczeniu czy raczej abym zostawił to wam. Jeśli wola będzie taka abym dalej to robił ze swojej strony dołożę wszelkich starań aby to zrobić jak najlepiej, jeśli będzie odwrotnie przyjmę to na klatę ;) a moja pomoc skieruje się w innym kierunku.
Tak więc czekam na decyzje :).
Pozdrawiam
Radosław L. (podpis pod filmikiem)

**Comment by MrSidoruk** [comment]
Myślę że jak nie spróbujesz to się nie dowiesz :) Zrób "demo" w postaci np tych linijek 4-5. Jeżeli będą błędy to ktoś poprawi :) Zawsze spoko jak więcej osób zerknie i wyłapie błędne spacje czy literówki. Ja sam tłumacze i podpieram się słownikiem szukając znaczeń i synonimów. Bo materiał jest raz że trudny - dwa że specyficzny. Czasami tłumaczenie dosłowne bywa bzdurne albo nie ma sensu w kontekście gry. Czasami też zamienia słowny żart w coś sztywnego:p Chyba że serio nie czujesz się na siłach.

**Comment by Kiwiutek** [comment]
Ja 50 % robiłem z pomocą słowników i google translatora opierając się o gramatykę jaką nauczyłem się w szkole. Były błędy, ale i tak ktoś to poprawi ew. wyjdzie w praniu. Zawsze przy tym co nie wiesz możesz dać "?" na początku, a w komentarzu napisać co jest do dopisania.

**Comment by Borgsc2** [comment]
To w takim razie będę dalej siedział nad lokalizacją

Mała informacja. Udało mi się zmienić nick na zbliżony do tego z którego praktycznie wszędzie obecnie korzystam.

**Comment by Viking-90** [comment]
Ja zrobię 7 do 10

**Comment by Stashkin** [comment]
@Borgsc2 - Działaj ;) Poprawimy. Ja też podpieram się słownikiem, ale do tego mam rozeznanie mniej więcej w grze i cóż... mój rocznik miał sporo styczności z angielskim, więc jako niedoszły filolog tegoż języka teraz spełniam się przy fanowskiej lokalizacji :D
I chwilowo wpisałem Cię na linijki 4k - 5k, żebyś nie czuł się przytłoczony ;)

Zrobiłem zatem pełny update obowiązków. Pamiętajcie, że podczas sprawdzania możecie kliknąć taki [+] przy linijkach kodu innego tłumaczącego i dodać swój komentarz. Najlepiej rozpocząć REVIEW i po dodaniu wszystkich uwag zatwierdzić wszystkie swoje uwagi za jednym zamachem ;)
