### ISSUE TITLE
Nowa wersja

### ISSUE THREAD

**Issue by Borgsc2** [Kiwiutek/Oxygen-Not-Included-Spolszczenie#27]
Pojawiła się nowa aktualizacja gry.

Aby zainstalować należy wybrać zakładkę Beta we właściwościach  a następnie wybrać z rozwijanej listy: 
- thermal_upgrade_preview

Aktualizacja przynosi ze sobą zmiany w pliku tłumaczeń dodając nowe teksty i modyfikując niektóre z nich.
Niestety dodane teksty pojawiają się zarówno na początku pliku jak i pośród już istniejących.

**Comment by Kiwiutek** [comment]
To nie jest problem kolo 21 zajmę się upgradem plików w nowe słowa.

**Comment by Kiwiutek** [comment]
Nowe linijki dodam osobno do plikow

**Comment by Kiwiutek** [comment]
Co wniosła aktualizacja bo akurat biegam i nie ma mnie przy laptopie?

**Comment by Borgsc2** [comment]
Z tym to że nowe linie to nie problem to wiem gorzej z tymi które się zmieniły np:
Było:

#. STRINGS.BUILDING.STATUSITEMS.BROKEN.TOOLTIP
msgctxt "STRINGS.BUILDING.STATUSITEMS.BROKEN.TOOLTIP"
msgid "This building was broken by a <style=\"stress\">Stressed</style> Duplicant\n\nIt must be repaired"
msgstr ""

Jest: 
#. STRINGS.BUILDING.STATUSITEMS.BROKEN.TOOLTIP
msgctxt "STRINGS.BUILDING.STATUSITEMS.BROKEN.TOOLTIP"
msgid "This building received damage {DamageInfo}"
msgstr ""

Będzie trzeba dokładnie sprawdzić gdzie zmiany występują i je również wyszczególnić, tak aby osoby tłumaczące uwzględniły te zmiany w swojej partii pliku.

Co do zmian zaraz postaram się je wysupłać.

**Comment by Borgsc2** [comment]
Zmiany

-  New ice biome
- New Space Heater, Liquid Tepidizer and Textile Factory buildings
- New plants
- New Duplicant temperature sensitivity and diseases
- Buildings can now overheat
- Pipes can burst and circuits can overload

**Comment by Borgsc2** [comment]
Testowanie aktualizacji zalecam na nowym save ze względu na ostrzeżenie na forum.

Current save files will not be compatible with this build

**Comment by Kiwiutek** [comment]
Mam prawie gotowe 👍

**Comment by Stashkin** [comment]
No w końcu więcej realizmu :> Skończy się zamykanie baterii w szczelnych pomieszczeniach. Trzeba będzie mądrzej budować sieci. Biom Lodowy pomoże w schładzaniu, mam nadzieję. Ciekawe, co robię te nowe budynki ;)

**Comment by Kiwiutek** [comment]
Aktualizacja plików zrobiona - biorę się za linijki, które odpadły.
